### ISSUE TITLE
README does not explain anything

### ISSUE THREAD

**Issue by tconn89** [whendricso/MultiGame#1]
How do I install the software?
Is there any demonstrations of what the tool can do?
Can I use the tool to create a vehicle system?

**Comment by whendricso** [comment]
Hey Ty, thanks for asking these questions! As MultiGame is very new, we don't have any tutorials yet. But it can be installed just by opening Unity with your desired project and then double-clicking the MultiGame .unitypackage file.

Flying vehicles can be created with MultiGame, and many other features as well especially features that are contained in most 3D games such as movement, health, construction, cinematics, and object interactions.

We have another update slated to come out soon which will include tutorials and updates :)

**Comment by whendricso** [comment]
Fixed!
